"""001_initial_schema

Revision ID: 3392b958c074
Revises: 
Create Date: 2026-09-24 11:11:34.397013
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3392b958c074'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tenant_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_tenants_slug')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_disciplines_tenant_slug')
    )
    op.create_index(op.f('ix_disciplines_tenant_id'), 'disciplines', ['tenant_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('discipline', sa.String(length=100), nullable=False),
    sa.Column('subdiscipline', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('preview', sa.Text(), nullable=False),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('authors_meta', sa.JSON(), nullable=True),
    sa.Column('volume', sa.String(length=50), nullable=True),
    sa.Column('issue', sa.String(length=50), nullable=True),
    sa.Column('pages', sa.String(length=50), nullable=True),
    sa.Column('issn', sa.String(length=20), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('publisher', sa.String(length=500), nullable=True),
    sa.Column('short_container_title', sa.String(length=200), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('publication_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_resources_tenant_slug')
    )
    op.create_index('ix_resources_abstract_trgm', 'resources', ['abstract'], unique=False, postgresql_using='gin', postgresql_ops={'abstract': 'gin_trgm_ops'})
    op.create_index(op.f('ix_resources_discipline'), 'resources', ['discipline'], unique=False)
    op.create_index(op.f('ix_resources_doi'), 'resources', ['doi'], unique=False)
    op.create_index(op.f('ix_resources_subdiscipline'), 'resources', ['subdiscipline'], unique=False)
    op.create_index('ix_resources_tenant_created', 'resources', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_resources_tenant_id'), 'resources', ['tenant_id'], unique=False)
    op.create_index('ix_resources_tenant_type_created', 'resources', ['tenant_id', 'type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_resources_title_trgm', 'resources', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index(op.f('ix_resources_type'), 'resources', ['type'], unique=False)
    op.create_index(op.f('ix_resources_venue'), 'resources', ['venue'], unique=False)
    op.create_index(op.f('ix_resources_year'), 'resources', ['year'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_roles_tenant_name')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('tenant_hosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_hosts_host'), 'tenant_hosts', ['host'], unique=True)
    op.create_index(op.f('ix_tenant_hosts_tenant_id'), 'tenant_hosts', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('refresh_token_version', sa.Integer(), nullable=False),
    sa.Column('totp_secret_encrypted', sa.String(length=512), nullable=True),
    sa.Column('totp_backup_codes_hashed', sa.String(length=2048), nullable=True),
    sa.Column('totp_enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_last_used_counter', sa.Integer(), nullable=True),
    sa.Column('webauthn_credentials', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('orcid', sa.String(length=200), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_users_tenant_username')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index('ix_users_tenant_orcid', 'users', ['tenant_id', 'orcid'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('author_follows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'author_name', name='uq_author_follows_tenant_user_author')
    )
    op.create_index(op.f('ix_author_follows_author_name'), 'author_follows', ['author_name'], unique=False)
    op.create_index(op.f('ix_author_follows_tenant_id'), 'author_follows', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_author_follows_user_id'), 'author_follows', ['user_id'], unique=False)
    op.create_table('discipline_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'discipline', name='uq_discipline_subscriptions_tenant_user_discipline')
    )
    op.create_index(op.f('ix_discipline_subscriptions_discipline'), 'discipline_subscriptions', ['discipline'], unique=False)
    op.create_index(op.f('ix_discipline_subscriptions_tenant_id'), 'discipline_subscriptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_discipline_subscriptions_user_id'), 'discipline_subscriptions', ['user_id'], unique=False)
    op.create_table('doi_registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('registered_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doi_registrations_doi'), 'doi_registrations', ['doi'], unique=False)
    op.create_index(op.f('ix_doi_registrations_registered_by'), 'doi_registrations', ['registered_by'], unique=False)
    op.create_index(op.f('ix_doi_registrations_resource_id'), 'doi_registrations', ['resource_id'], unique=False)
    op.create_index(op.f('ix_doi_registrations_tenant_id'), 'doi_registrations', ['tenant_id'], unique=False)
    op.create_table('file_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sha256', name='uq_file_assets_tenant_sha256')
    )
    op.create_index(op.f('ix_file_assets_sha256'), 'file_assets', ['sha256'], unique=False)
    op.create_index(op.f('ix_file_assets_tenant_id'), 'file_assets', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_file_assets_uploaded_by'), 'file_assets', ['uploaded_by'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('related_id', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_id_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('reading_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'resource_id', name='uq_reading_history_tenant_user_resource')
    )
    op.create_index(op.f('ix_reading_history_resource_id'), 'reading_history', ['resource_id'], unique=False)
    op.create_index(op.f('ix_reading_history_tenant_id'), 'reading_history', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_reading_history_user_id'), 'reading_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_reading_history_viewed_at'), 'reading_history', ['viewed_at'], unique=False)
    op.create_table('reading_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'name', name='uq_reading_lists_tenant_user_name')
    )
    op.create_index(op.f('ix_reading_lists_tenant_id'), 'reading_lists', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_reading_lists_user_id'), 'reading_lists', ['user_id'], unique=False)
    op.create_table('subdisciplines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discipline_id', 'slug', name='uq_subdisciplines_discipline_slug')
    )
    op.create_index(op.f('ix_subdisciplines_discipline_id'), 'subdisciplines', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_subdisciplines_tenant_id'), 'subdisciplines', ['tenant_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('authors', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('discipline', sa.String(length=100), nullable=False),
    sa.Column('subdiscipline', sa.String(length=100), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('jel_codes', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('preview', sa.Text(), nullable=False),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('corresponding_author_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('editor_note', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_resource_id'), 'submissions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_submissions_reviewed_by'), 'submissions', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_submitted_by'), 'submissions', ['submitted_by'], unique=False)
    op.create_index(op.f('ix_submissions_tenant_id'), 'submissions', ['tenant_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'role_id', name='uq_user_roles_tenant_user_role')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_tenant_id'), 'user_roles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('reading_list_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reading_list_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reading_list_id'], ['reading_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reading_list_id', 'resource_id', name='uq_reading_list_item_resource')
    )
    op.create_index(op.f('ix_reading_list_items_reading_list_id'), 'reading_list_items', ['reading_list_id'], unique=False)
    op.create_index(op.f('ix_reading_list_items_resource_id'), 'reading_list_items', ['resource_id'], unique=False)
    op.create_index(op.f('ix_reading_list_items_tenant_id'), 'reading_list_items', ['tenant_id'], unique=False)
    op.create_table('review_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'reviewer_id', name='uq_review_assignment_submission_reviewer')
    )
    op.create_index(op.f('ix_review_assignments_assigned_by'), 'review_assignments', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_review_assignments_reviewer_id'), 'review_assignments', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_review_assignments_status'), 'review_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_review_assignments_submission_id'), 'review_assignments', ['submission_id'], unique=False)
    op.create_index(op.f('ix_review_assignments_tenant_id'), 'review_assignments', ['tenant_id'], unique=False)
    op.create_table('submission_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'version', name='uq_submission_version_number')
    )
    op.create_index(op.f('ix_submission_versions_submission_id'), 'submission_versions', ['submission_id'], unique=False)
    op.create_index(op.f('ix_submission_versions_tenant_id'), 'submission_versions', ['tenant_id'], unique=False)
    op.create_table('review_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(length=32), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('comments_to_editor', sa.Text(), nullable=True),
    sa.Column('comments_to_author', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['review_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', name='uq_review_report_assignment')
    )
    op.create_index(op.f('ix_review_reports_assignment_id'), 'review_reports', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_review_reports_tenant_id'), 'review_reports', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_reports_tenant_id'), table_name='review_reports')
    op.drop_index(op.f('ix_review_reports_assignment_id'), table_name='review_reports')
    op.drop_table('review_reports')
    op.drop_index(op.f('ix_submission_versions_tenant_id'), table_name='submission_versions')
    op.drop_index(op.f('ix_submission_versions_submission_id'), table_name='submission_versions')
    op.drop_table('submission_versions')
    op.drop_index(op.f('ix_review_assignments_tenant_id'), table_name='review_assignments')
    op.drop_index(op.f('ix_review_assignments_submission_id'), table_name='review_assignments')
    op.drop_index(op.f('ix_review_assignments_status'), table_name='review_assignments')
    op.drop_index(op.f('ix_review_assignments_reviewer_id'), table_name='review_assignments')
    op.drop_index(op.f('ix_review_assignments_assigned_by'), table_name='review_assignments')
    op.drop_table('review_assignments')
    op.drop_index(op.f('ix_reading_list_items_tenant_id'), table_name='reading_list_items')
    op.drop_index(op.f('ix_reading_list_items_resource_id'), table_name='reading_list_items')
    op.drop_index(op.f('ix_reading_list_items_reading_list_id'), table_name='reading_list_items')
    op.drop_table('reading_list_items')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_tenant_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_submissions_tenant_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_submitted_by'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_reviewed_by'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_resource_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_subdisciplines_tenant_id'), table_name='subdisciplines')
    op.drop_index(op.f('ix_subdisciplines_discipline_id'), table_name='subdisciplines')
    op.drop_table('subdisciplines')
    op.drop_index(op.f('ix_reading_lists_user_id'), table_name='reading_lists')
    op.drop_index(op.f('ix_reading_lists_tenant_id'), table_name='reading_lists')
    op.drop_table('reading_lists')
    op.drop_index(op.f('ix_reading_history_viewed_at'), table_name='reading_history')
    op.drop_index(op.f('ix_reading_history_user_id'), table_name='reading_history')
    op.drop_index(op.f('ix_reading_history_tenant_id'), table_name='reading_history')
    op.drop_index(op.f('ix_reading_history_resource_id'), table_name='reading_history')
    op.drop_table('reading_history')
    op.drop_index('ix_notifications_user_id_created_at', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_file_assets_uploaded_by'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_tenant_id'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_sha256'), table_name='file_assets')
    op.drop_table('file_assets')
    op.drop_index(op.f('ix_doi_registrations_tenant_id'), table_name='doi_registrations')
    op.drop_index(op.f('ix_doi_registrations_resource_id'), table_name='doi_registrations')
    op.drop_index(op.f('ix_doi_registrations_registered_by'), table_name='doi_registrations')
    op.drop_index(op.f('ix_doi_registrations_doi'), table_name='doi_registrations')
    op.drop_table('doi_registrations')
    op.drop_index(op.f('ix_discipline_subscriptions_user_id'), table_name='discipline_subscriptions')
    op.drop_index(op.f('ix_discipline_subscriptions_tenant_id'), table_name='discipline_subscriptions')
    op.drop_index(op.f('ix_discipline_subscriptions_discipline'), table_name='discipline_subscriptions')
    op.drop_table('discipline_subscriptions')
    op.drop_index(op.f('ix_author_follows_user_id'), table_name='author_follows')
    op.drop_index(op.f('ix_author_follows_tenant_id'), table_name='author_follows')
    op.drop_index(op.f('ix_author_follows_author_name'), table_name='author_follows')
    op.drop_table('author_follows')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_tenant_orcid', table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenant_hosts_tenant_id'), table_name='tenant_hosts')
    op.drop_index(op.f('ix_tenant_hosts_host'), table_name='tenant_hosts')
    op.drop_table('tenant_hosts')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_resources_year'), table_name='resources')
    op.drop_index(op.f('ix_resources_venue'), table_name='resources')
    op.drop_index(op.f('ix_resources_type'), table_name='resources')
    op.drop_index('ix_resources_title_trgm', table_name='resources', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_resources_tenant_type_created', table_name='resources')
    op.drop_index(op.f('ix_resources_tenant_id'), table_name='resources')
    op.drop_index('ix_resources_tenant_created', table_name='resources')
    op.drop_index(op.f('ix_resources_subdiscipline'), table_name='resources')
    op.drop_index(op.f('ix_resources_doi'), table_name='resources')
    op.drop_index(op.f('ix_resources_discipline'), table_name='resources')
    op.drop_index('ix_resources_abstract_trgm', table_name='resources', postgresql_using='gin', postgresql_ops={'abstract': 'gin_trgm_ops'})
    op.drop_table('resources')
    op.drop_index(op.f('ix_disciplines_tenant_id'), table_name='disciplines')
    op.drop_table('disciplines')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
