blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/weed33834/scholarhub/issues
    about: For questions and general discussion, please open an issue with the `question` label.
