import { test, expect } from '@playwright/test'
import { ADMIN, loginViaUi } from './helpers'

// 管理员创建资源(catalog/new.tsx)。
// 校验:
// - 非 admin 用户被守卫挡回 /login
// - 表单字段齐全
// - 创建一条 paper 资源 → 跳详情页 → 详情页显示标题/作者/摘要
// - 创建一条 book 资源（不同 type + 选填字段）
// - 取消按钮回到 /catalog

test.describe('admin: create resource', () => {
  test.beforeEach(async ({ page }) => {
    await loginViaUi(page, ADMIN)
  })

  test('non-admin cannot reach /catalog/new', async ({ browser }) => {
    // 单独建一个 context 不登录
    const ctx = await browser.newContext()
    const page = await ctx.newPage()
    await page.goto('/catalog/new')
    await expect(page).toHaveURL(/\/login/)
    await ctx.close()
  })

  test('admin can open new resource form and see all required fields', async ({ page }) => {
    await page.goto('/catalog/new')
    await expect(page.getByRole('heading', { name: '新建资源' })).toBeVisible()
    const labels = ['类型', '年份', '标题', '作者（逗号分隔）', '学科', '摘要'] as const
    for (const label of labels) {
      // exact:true 避免"学科"误匹配"子学科"、"摘要"误匹配"预览（...摘要）"
      await expect(page.getByLabel(label, { exact: true })).toBeVisible()
    }
    await expect(page.getByRole('button', { name: '创建' })).toBeVisible()
    await expect(page.getByRole('button', { name: '取消' })).toBeVisible()
  })

  test('create a paper resource — happy path', async ({ page }) => {
    await page.goto('/catalog/new')
    const title = `E2E Paper ${Date.now()}`
    await page.getByLabel('标题').fill(title)
    await page.getByLabel('作者（逗号分隔）').fill('Alice Smith, Bob Jones')
    await page.getByLabel('学科', { exact: true }).fill('computer science')
    await page.getByLabel('摘要', { exact: true }).fill('This is a test abstract generated by E2E.')
    // 默认 type=paper, publication_status=published, year=当前年, language=en
    await page.getByRole('button', { name: '创建' }).click()

    // toast 成功
    await expect(page.getByText('创建成功')).toBeVisible({ timeout: 5_000 })
    // 跳到 /catalog/$resourceId
    await expect(page).toHaveURL(/\/catalog\/\d+/, { timeout: 10_000 })
    // 详情页显示刚提交的标题
    await expect(page.getByRole('heading', { name: title })).toBeVisible()
    await expect(page.getByText('Alice Smith, Bob Jones')).toBeVisible()
    // 详情页摘要可能在两处显示（预览 + 完整摘要），用 first
    await expect(page.getByText('This is a test abstract generated by E2E.').first()).toBeVisible()
  })

  test('create a book with optional fields', async ({ page }) => {
    await page.goto('/catalog/new')
    // 改类型为 book
    await page.getByLabel('类型').click()
    await page.getByRole('option', { name: '图书' }).click()
    const title = `E2E Book ${Date.now()}`
    await page.getByLabel('标题').fill(title)
    await page.getByLabel('作者（逗号分隔）').fill('Carol Lee')
    await page.getByLabel('学科', { exact: true }).fill('mathematics')
    await page.getByLabel('摘要', { exact: true }).fill('A book about numbers.')
    // 选填
    await page.getByLabel('出版物').fill('Springer')
    await page.getByLabel('ISBN').fill('978-3-16-148410-0')
    await page.getByLabel('DOI').fill('10.1000/e2e-book')
    await page.getByLabel('标签（逗号分隔）').fill('algebra, geometry')
    await page.getByRole('button', { name: '创建' }).click()

    await expect(page.getByText('创建成功')).toBeVisible({ timeout: 5_000 })
    await expect(page).toHaveURL(/\/catalog\/\d+/, { timeout: 10_000 })
    await expect(page.getByRole('heading', { name: title })).toBeVisible()
    // 详情页元数据区显示 ISBN / DOI / 标签
    await expect(page.getByText('978-3-16-148410-0')).toBeVisible()
    await expect(page.getByText('10.1000/e2e-book')).toBeVisible()
    await expect(page.getByText('algebra')).toBeVisible()
    await expect(page.getByText('geometry')).toBeVisible()
  })

  test('cancel button returns to /catalog', async ({ page }) => {
    await page.goto('/catalog/new')
    await page.getByRole('button', { name: '取消' }).click()
    await expect(page).toHaveURL(/\/catalog$/)
  })

  test('create without required title fails with validation', async ({ page }) => {
    await page.goto('/catalog/new')
    // 必填字段留空，提交按钮被 HTML5 required 拦截，浏览器不发请求
    await page.getByLabel('摘要', { exact: true }).fill('No title here')
    await page.getByRole('button', { name: '创建' }).click()
    // 仍停留在 new 页面
    await expect(page).toHaveURL(/\/catalog\/new/)
    await expect(page.getByRole('heading', { name: '新建资源' })).toBeVisible()
  })

  test('admin can edit an existing resource via detail page', async ({ page }) => {
    // 先建一条
    await page.goto('/catalog/new')
    const title = `E2E Edit ${Date.now()}`
    await page.getByLabel('标题').fill(title)
    await page.getByLabel('作者（逗号分隔）').fill('Edit Author')
    await page.getByLabel('学科', { exact: true }).fill('physics')
    await page.getByLabel('摘要', { exact: true }).fill('Original abstract.')
    await page.getByRole('button', { name: '创建' }).click()
    await expect(page).toHaveURL(/\/catalog\/\d+/, { timeout: 10_000 })

    // 点编辑
    await page.getByRole('button', { name: '编辑' }).click()
    await expect(page.getByText('编辑资源')).toBeVisible()
    // 改标题
    const newTitle = `${title} (v2)`
    await page.getByLabel('标题').fill(newTitle)
    await page.getByRole('button', { name: '保存' }).click()
    await expect(page.getByText('已更新')).toBeVisible({ timeout: 5_000 })
    // 详情页显示新标题
    await expect(page.getByRole('heading', { name: newTitle })).toBeVisible()
  })

  test('admin can delete a resource via detail page', async ({ page }) => {
    // 先建一条
    await page.goto('/catalog/new')
    const title = `E2E Delete ${Date.now()}`
    await page.getByLabel('标题').fill(title)
    await page.getByLabel('作者（逗号分隔）').fill('Del Author')
    await page.getByLabel('学科', { exact: true }).fill('biology')
    await page.getByLabel('摘要', { exact: true }).fill('To be deleted.')
    await page.getByRole('button', { name: '创建' }).click()
    await expect(page).toHaveURL(/\/catalog\/\d+/, { timeout: 10_000 })

    // 点删除
    await page.getByRole('button', { name: '删除' }).click()
    // ConfirmDialog 出现
    await page.getByRole('button', { name: '删除', exact: true }).click()
    await expect(page.getByText('已删除')).toBeVisible({ timeout: 5_000 })
    // 跳回 catalog 列表
    await expect(page).toHaveURL(/\/catalog$/)
  })
})
